### ISSUE TITLE
socketlen is not found

### ISSUE THREAD

**Issue by edusierraf** [xebd/accel-ppp#10]
Hello!

I tried to compile version 1.11.1 and have problem with postgresql support:

[ 65%] Building C object accel-pppd/logs/CMakeFiles/log_pgsql.dir/log_pgsql.c.o
In file included from /usr/src/accel-ppp-1.11.1/accel-pppd/include/ap_session.h:4:0,
                 from /usr/src/accel-ppp-1.11.1/accel-pppd/logs/log_pgsql.c:11:
/usr/src/accel-ppp-1.11.1/accel-pppd/include/ap_net.h:7:52: error: unknown type name ‘socklen_t’
  int (*connect)(int sock, const struct sockaddr *, socklen_t len);
                                                    ^
/usr/src/accel-ppp-1.11.1/accel-pppd/include/ap_net.h:8:49: error: unknown type name ‘socklen_t’
  int (*bind)(int sock, const struct sockaddr *, socklen_t len);
                                                 ^
/usr/src/accel-ppp-1.11.1/accel-pppd/include/ap_net.h:11:93: error: unknown type name ‘socklen_t’
  ssize_t (*recvfrom)(int sock, void *buf, size_t len, int flags, struct sockaddr *src_addr, socklen_t *addrlen);
                                                                                             ^
/usr/src/accel-ppp-1.11.1/accel-pppd/include/ap_net.h:13:104: error: unknown type name ‘socklen_t’
  ssize_t (*sendto)(int sock, const void *buf, size_t len, int flags, const struct sockaddr *dest_addr, socklen_t addrlen);
                                                                                                        ^
/usr/src/accel-ppp-1.11.1/accel-pppd/include/ap_net.h:15:76: error: unknown type name ‘socklen_t’
  int (*setsockopt)(int sockfd, int level, int optname, const void *optval, socklen_t optlen);

After some research, I found a bugfix at https://github.com/xebd/accel-ppp/pull/2/commits/68008248259dfaa2fde91f8697db889971056bb3. 

Actual version of log_pgsql.c	have this issue.

My environment:  Ubuntu 16.04.2 LTS  (GNU/Linux 4.4.0-72-generic x86_64)

Best regards,

Eduardo

**Comment by xebd** [comment]
commit e78709bfd05f003243c157c654f8d58ffefffaee
