### ISSUE TITLE
README clarification

### ISSUE THREAD

**Issue by thomas-mangin** [xebd/accel-ppp#106]
```
Warning !!!
-----------
1. The pptp driver conflicts with ip_gre driver (in kernel), so make sure that ip_gre is not built-in or loaded at run time (don't matter if you have 2.6.37 or later kernel).
```

Should it be read as:
 - the issue is not present with recent kernels (2.6.37 or later) - my preferred reading :-)
 - the issue is present, it does not matter if you have a recent kernel (2.6.37 or later)

Not that 2.6.37 is that recent. It was released in 2011 ...

**Comment by DmitriyEshenko** [comment]
You do not need build pptp module in modern kernel higher than 2.6.37, pptp module already there

**Comment by thomas-mangin** [comment]
Thank you - closing.
