### ISSUE TITLE
How can i get User's NAT logs?? Any facility in this version?

### ISSUE THREAD

**Issue by imdadk** [xebd/accel-ppp#119]
I want to use this tool in my network but my half network is on fake/private ips. i have to save the private ips NAT logs for submit to the government if any Cyber Crime query arrives, for that how can i get NAT logs?

**Comment by DmitriyEshenko** [comment]
Hi, are you seriously? This question not about accel-ppp.
Use netflow software in this case or copy conntrack table.

**Comment by imdadk** [comment]
Ohh sorry.. I am trying to pool request.. sorry by mistake i create issue..

AGAIN S O R R Y..
