### ISSUE TITLE
vlan with PPPoE not working / Vlan not created with vlan_mon

### ISSUE THREAD

**Issue by imdadk** [xebd/accel-ppp#120]
i was already loaded vlan_mon driver in kernel its shows in list module, after that vlan_mon not working and not create vlan interfaces. I was tried on ubuntu 14.x and also on ubuntu 16.x.

My running configuration of pppoe module is

[pppoe]
verbose=1
#max-starting=0
#ac-name=xxx
#service-name=yyy
#pado-delay=0
#pado-delay=0,100:100,200:200,-1:500
called-sid=mac
#tr101=1
#padi-limit=0
#ip-pool=pppoe
ipv6-pool=pppoe-v6
ipv6-pool-delegate=pppoe-v6-pd
#ifname=pppoe%d
#sid-uppercase=0
vlan-mon=ens34.1,1-4000
#vlan-timeout=60
vlan-name=%I.%N
#interface=eth1,padi-limit=1000,net=accel-dp
interface=re:ens34\.
interface=ens34

**Comment by DmitriyEshenko** [comment]
Do you have `ens34.1` interface?

**Comment by imdadk** [comment]
no, only ens34 interface. but i was also try like vlan-mon=ens34,1-4000...

**Comment by DmitriyEshenko** [comment]
Try next
```
vlan-mon=ens34,1-4000
vlan-name=%I.%N
interface=re:ens34\.\d+
```
See also log with level debug `[log]level=5` for more information.

**Comment by imdadk** [comment]
tried this, debug with level=5, seen debug log, but its not shows any thing about the pppoe interface OR vlan interface or something.

**Comment by DmitriyEshenko** [comment]
Maybe you need also add `verbose=1` for `[ppp]` and `[pppoe]` sections and restart accel-ppp. `accel-cmd restart`

**Comment by imdadk** [comment]
It is already verbose=1 in those both sections. also tried after restarting daemon. But nothing happen, all logs like accel-ppp.log/core.log/emerg.log/auth-fail.log nothing shows about vlan. infact also checked syslog. :-)

**Comment by DmitriyEshenko** [comment]
1. Check with tcpdump when pppoe client connect in some vlan
```
tcpdump -n -i ens34 -e -v
```
2. Look into accel-ppp.log when client connecting

**Comment by imdadk** [comment]
vlan-mon=ens34,1-4000
vlan-name=%I.%N
interface=re:ens34\.\d+


this configuration is ok for vlan in pppoe.
first of all this is not create any vlan. and not shows any thing in  **accel-cmd pppoe interface show**
