### ISSUE TITLE
Compile time error situation. /usr/include/linux/if.h:183:19: error:

### ISSUE THREAD

**Issue by dhpark21** [xebd/accel-ppp#127]
Centos 6.2 case
Linux test 2.6.32-754.28.1.el6.i686 #1 SMP Wed Mar 11 19:03:51 UTC 2020 i686 i686 i386 GNU/Linux
--
[root@test build]# make
[  1%] Building C object accel-pppd/triton/CMakeFiles/triton.dir/md.c.o
[  2%] Building C object accel-pppd/triton/CMakeFiles/triton.dir/timer.c.o
[  3%] Building C object accel-pppd/triton/CMakeFiles/triton.dir/triton.c.o
[  4%] Building C object accel-pppd/triton/CMakeFiles/triton.dir/conf_file.c.o
[  5%] Building C object accel-pppd/triton/CMakeFiles/triton.dir/loader.c.o
[  6%] Building C object accel-pppd/triton/CMakeFiles/triton.dir/log.c.o
[  7%] Building C object accel-pppd/triton/CMakeFiles/triton.dir/mempool.c.o
[  8%] Building C object accel-pppd/triton/CMakeFiles/triton.dir/event.c.o
Linking C shared library libtriton.so
[  8%] Built target triton
Scanning dependencies of target accel-pppd
[  9%] Building C object accel-pppd/CMakeFiles/accel-pppd.dir/memdebug.c.o
[ 10%] Building C object accel-pppd/CMakeFiles/accel-pppd.dir/session.c.o
[ 11%] Building C object accel-pppd/CMakeFiles/accel-pppd.dir/session_backup.c.o
[ 12%] Building C object accel-pppd/CMakeFiles/accel-pppd.dir/ifcfg.c.o
[ 13%] Building C object accel-pppd/CMakeFiles/accel-pppd.dir/net.c.o
In file included from /home/admin/SSTP/20200408/accel-ppp/accel-pppd/net.c:10:0:
/usr/include/linux/if.h:183:19: error: field ‘ifru_addr’ has incomplete type
   struct sockaddr ifru_addr;
                   ^
/usr/include/linux/if.h:184:19: error: field ‘ifru_dstaddr’ has incomplete type
   struct sockaddr ifru_dstaddr;
                   ^
/usr/include/linux/if.h:185:19: error: field ‘ifru_broadaddr’ has incomplete type
   struct sockaddr ifru_broadaddr;
                   ^
/usr/include/linux/if.h:186:19: error: field ‘ifru_netmask’ has incomplete type
   struct sockaddr ifru_netmask;
                   ^
/usr/include/linux/if.h:187:20: error: field ‘ifru_hwaddr’ has incomplete type
   struct  sockaddr ifru_hwaddr;
                    ^
/home/admin/SSTP/20200408/accel-ppp/accel-pppd/net.c:46:12: warning: ‘def_ns_fd’ defined but not used [-Wunused-variable]
 static int def_ns_fd;
            ^
make[2]: *** [accel-pppd/CMakeFiles/accel-pppd.dir/net.c.o] Error 1
make[1]: *** [accel-pppd/CMakeFiles/accel-pppd.dir/all] Error 2
make: *** [all] Error 2

**Comment by DmitriyEshenko** [comment]
Already fixed in org repo.
PR for this task https://github.com/xebd/accel-ppp/pull/128

**Comment by DmitriyEshenko** [comment]
@dhpark21 can you check and close this issue?
PR already merged.

**Comment by dhpark21** [comment]
Work Fine
Thanks
