### ISSUE TITLE
How many client connect at one server?

### ISSUE THREAD

**Issue by dhpark21** [xebd/accel-ppp#130]
How many vpn client connect at one server?
my case sstp only 100.
and, how can increase this?

Thanks

**Comment by DmitriyEshenko** [comment]
As I know `accel-ppp` does not limit this.
Check `accel-ppp` logs and see reason

**Comment by dhpark21** [comment]
Thanks.
my case 443 port connlimit 100
accel-ppp is not limit.
Thanks
