### ISSUE TITLE
SEGFAULT when cross compile onto arm based platform.

### ISSUE THREAD

**Issue by ericjbree** [xebd/accel-ppp#14]
When running a cross compiled accel-pppd (1.11.2) on an arm based platform (clearfog-pro) accel-pppd SEGFAULTs.  I compiled with the following cmake settings.

`-DBUILD_PPTP_DRIVER=FALSE -DBUILD_IPOE_DRIVER=FALSE -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DLOG_PGSQL=FALSE -DLOG_FILE=FALSE -DRADIUS=FALSE -DNETSNMP=TRUE -DLUA=FALSE -DLIB_SUFFIX=`

I tracked down the SEGFAULT to line 320 of accel-ppd/libnetlink/iputils.c and for me, commenting out the line worked.

**Comment by xebd** [comment]
sorry, i have no arm-based platform and can't debug it

**Comment by ericjbree** [comment]
And if I am able to provide a arm-based platform?  Like a clearfog pro.  Would you then be able to debug it?

**Comment by xebd** [comment]
yes, i can try

**Comment by ericjbree** [comment]
Can you please send me the address where you would like it sent if I can arrange it?

**Comment by alex-eri** [comment]
@ericjbree that about reproduce in `qemu-arm`? 
segfault often is linker problem. Are you using `musl` or `glibc`?

**Comment by ericjbree** [comment]
I can try to reproduce it in qemu-arm.  I am using musl as I run LEDE on a clearfog pro.
