### ISSUE TITLE
crash on snmpwalk

### ISSUE THREAD

**Issue by AFdefault** [xebd/accel-ppp#16]
if activ ppp interface > 0

comand: snmpwalk -m +ACCEL-PPP-MIB -v 2c -c xxxxx xxxxx ACCEL-PPP-MIB::accelPPPStat

say:
Error in packet.
Reason: (genError) A general failure occured
Failed object: ACCEL-PPP-MIB::statPPPOEActive.0

and crash accel-ppp
im use pppoe server

**Comment by xebd** [comment]
commit e959ea1bd262441a952ea0c807d553b4a9c38113
