### ISSUE TITLE
CONFIG_X86_X32 enabled but no binutils support

### ISSUE THREAD

**Issue by mluis** [xebd/accel-ppp#17]
Happens while running `make install`.

*msg* 

> arch/x86/Makefile:148: CONFIG_X86_X32 enabled but no binutils support

*pwd*

> /root/accel-ppp/build

**Comment by xebd** [comment]
this looks like not accel-ppp related

**Comment by mluis** [comment]
It happens when running make install from accel-ppp

**Comment by xebd** [comment]
what is your distro and build settings ?

**Comment by mluis** [comment]
Under `Ubuntu 16.04.3 LTS` was using cmake like:

`cmake -DBUILD_DRIVER_ONLY=FALSE -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DRADIUS=TRUE -DNETSNMP=FALSE ..`

Just pulled to the latest code. Didn't reproduced.
