### ISSUE TITLE
how to set pptp and l2tp use different network

### ISSUE THREAD

**Issue by digger-yu** [xebd/accel-ppp#174]
how to set pptp and l2tp use different network ip-pool

i setup a accel-ppp server ,  support pppoe pptp l2tp
my server have two network card
192.168.1.1is Intranet address

#####
[ip-pool]
gw-ip-address=192.168.1.1
#vendor=Cisco
#attr=Cisco-AVPair
attr=Framed-Pool
#192.168.0.2-255
192.168.1.2-255,name=pppoe
192.168.1.2-255,name=pptp
192.168.1.2-255,name=l2tp
#####
the current is pptp l2tp pppoe Network segment both is 192.168.1.0

how to set pptp and l2tp use different network ip-pool

**Comment by DmitriyEshenko** [comment]
Hi @digger-yu , you can use per protocol params `[pptp]ip-pool=pptp` and `[l2tp]ip-pool=l2tp`
