### ISSUE TITLE
SSTP over http, not tls

### ISSUE THREAD

**Issue by alex-eri** [xebd/accel-ppp#54]
Is it possible to make SSTP server run on http://? It needed to put vpn server behind nginx (or other proxy) and run with web site on same port.

**Comment by themiron** [comment]
yes, disable ssl and optionally enable proxy, bind to unix socket (if desired).
refer accel-ppp.conf.5, section [sstp] for more details

**Comment by alex-eri** [comment]
wiki pages are abandoned... so asked here

good manpage, thnx!
