### ISSUE TITLE
add default column ip6

### ISSUE THREAD

**Issue by zavndw** [xebd/accel-ppp#71]
pls add default column ip6 in show sessions

**Comment by mnik247** [comment]
@zavndw  you can do it in 'cli'
[cli]
verbose=1
telnet=127.0.0.1:2000
tcp=127.0.0.1:2001
sessions-columns=ifname,username,calling-sid,called-sid,ip,ip6,rate-limit,type,state,rx-bytes,tx-bytes,uptime
