### ISSUE TITLE
kernel network namespaces

### ISSUE THREAD

**Issue by alex-eri** [xebd/accel-ppp#82]
what if i move some ppp connections to different netns?

**Comment by DmitriyEshenko** [comment]
Hi, I think this idea not bad, in accel-ppp exist some commits for `netns`. You can sets `netns` by RADIUS.
https://github.com/xebd/accel-ppp/commit/e0cca4344f70b9c9e23e3c6a7e17c8e93c765184
https://accel-ppp.org/forum/viewtopic.php?t=670

**Comment by alex-eri** [comment]
Didn`t know that it already done. Thanks
